### ISSUE TITLE
Crash on tvos 13.4

### ISSUE THREAD

**Issue by CokePokes** [RealKGB/Spartan#1]
Crash on load using the latest deb in releases

**Comment by WhitetailAni** [comment]
Crashlog please?

**Comment by WhitetailAni** [comment]
Should be resolved with latest release, if it's the bug I think it is

**Comment by WhitetailAni** [comment]
No further info from user, fairly certain bug has been resolved with [beta 6.1](https://github.com/WhitetailAni/Spartan/releases/tag/0.7.1), closing.
