### ISSUE TITLE
File is invalid or not supported + Creating Files

### ISSUE THREAD

**Issue by MattBryanB** [RealKGB/Spartan#2]
Hello, thank you so much for the work you've done with this app. I'm running the new release candidate on AppleTV5,3. Having trouble opening several files, most importantly in my current predicament being /private/etc/master.passwd  

I've inexplicably somehow forgotten my root password and am attempting to edit the master.passwd file to reset the password to standard default.  However, I keep getting "The file is invalid or not supported. Please make sure the file is not corrupted and then try again."  I suppose it's possible the file may be corrupted but I can't see how that could be. Is there a way to open this file? 

As a workaround I tried creating a new file in Documents folder called master.passwd however the file never shows up anywhere in that directory. Could it maybe be creating the file elsewhere? It also appears the web server function is not working. I could not pull it up at all

Open to other possible solutions to reset root password if anything comes to mind. There used to be a deb file for iOS floating around that could achieve this but I haven't found anything comparable for tvOS. Thanks again for all your hard work on this project.

**Comment by WhitetailAni** [comment]
Ok, so the root helper issue isn't just me - thanks!
I can investigate master.passwd too, thank you!

**Comment by WhitetailAni** [comment]
Creating files has been addressed with [1.0RC2](https://github.com/WhitetailAni/Spartan/releases/tag/1.0.0RC2)

master.passwd is a valid ASCII, UTF8, UTF16, or UTF32 file on tvOS and so it cannot be edited by the text editor. Why this is the case I do not know.

**Comment by WhitetailAni** [comment]
I should clarify that on stock tvOS 15.0, no jailbreak bootstrap, master.passwd is not editable by Spartan except by the hex editor.
